services:
  workspace:
    build:
      context: ./workspace/docker
      dockerfile: Dockerfile 
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PWD: ${DB_PASSWORD}
    volumes:
      - type: bind
        source: ..
        target: /workspace
    tty: true

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      # - type: bind
      #   source: ./db/init
      #   target: /docker-entrypoint-initdb.d

volumes:
  mysql-data: